#!/usr/bin/env bash
set -e # halt script on error

npm install -g lighthouse
npm install -g firebase-tools
bundle install
bundle exec jekyll build
lighthouse --output=pretty https://mukilane.github.io
firebase database:set /data/posts _site/assets/posts.json --confirm --token $FIREBASE_TOKEN