#!/usr/bin/env bash
set -e # halt script on error

npm install -g firebase-tools
npm install -g lighthouse
bundle install
bundle exec jekyll build
lighthouse --chrome-flags="--no-sandbox=true" https://mukilane.github.io/
firebase use mukilane
firebase database:set /data/posts _site/assets/posts.json --confirm --token $FIREBASE_TOKEN
